import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';

import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";

import Providers from "./providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" {...mantineHtmlProps} suppressHydrationWarning>
            <head>
                <ColorSchemeScript />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased
                !bg-[#F3F3F1] dark:bg-[#1A1B1E] text-black dark:text-[#F3F3F1]
                transition-colors duration-200 ease-in-out
                dark:[&_.mantine-Overlay-root]:bg-[#1A1B1E] dark:[&_.mantine-ModalBase-root]:bg-[#1A1B1E]
                dark:[&_.mantine-ModalBase-root]:text-[#F3F3F1]
                dark:[&_.mantine-ModalBase-root]:border-[#1A1B1E]
                `}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
